config/routes.rb
Rails.application.routes.draw do
  root :to => 'sections#index'

  resources :sections do
    resources :lessons
  end

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates :title, :body, :number, :presence => true
  belongs_to :section

  def next
    Lesson.find_by(number: number + 1)
  end

  def previous
    Lesson.find_by(number: number - 1)
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :title, :presence => true
  has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def new
    @section = Section.find(params[:section_id])
    @lesson = Lesson.new
    render :new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    @lesson.number = @section.lessons.length + 1
    if @lesson.save
      redirect_to section_path(@section)
    else
      render :new
    end
  end

  def show
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_path(@section)
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(params[:lesson])
      redirect_to section_path(@lesson.section)
    else
      render :edit
    end
  end

  def lesson_params
    params.require(:lesson).permit(:title, :body, :number)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def new
    @section = Section.new
  end

  def show
    @section = Section.find(params[:id])
  end

  def edit
    @section = Section.find(params[:id])
  end

  def create
    @section = Section.new(params[:section])
    if @section.save
      redirect_to sections_path
    else
      render :new
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

  def update
    @section= Section.find(params[:id])
    if @section.update(params[:section])
      redirect_to sections_path
    else
      render :edit
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' rel='stylesheet'  type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for [@section, @lesson] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :body %>
<%= f.text_area :body, size: "80x30" %><br>
<%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit <%= @lesson.title %> </h1>

<%= render 'form' %>

app/views/lessons/new.html.erb
<h1>Add a new lesson to <%= @section.title %></h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<h1><%= @lesson.title %> in <%= @section.title %></h1>

<p>
  <%= @lesson.body %>
</p>

<% if @lesson.previous %>
<%= link_to "previous lesson", section_lesson_path(@section, @lesson.previous) %> |
<% end %>
<% if @lesson.next %>
<%= link_to "next lesson", section_lesson_path(@section, @lesson.next) %>
<% end %>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<%= form_for @section do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit section</h1>

<%= render 'form' %>

app/views/sections/index.html.erb
<h1>Sections</h1>
<p>
  <%= link_to "Add a new section", new_section_path %>
</p>
<ul>
  <% @sections.each do |section| %>
  <li><%= link_to section.title, section_path(section) %></li>
  <% end %>
</ul>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

app/views/sections/show.html.erb
<h1><%= @section.title %></h1>
<% if @section.lessons.any? %>
<h4>Here are the lessons for this section:</h4>
<ul>
  <% @section.lessons.each do |lesson| %>
  <li>
    <%= link_to lesson.title, section_lesson_path(@section, lesson) %> |
    <%= link_to "Edit", edit_section_lesson_path(@section, lesson) %> |
    <%= link_to "Delete", section_lesson_path(@section, lesson),
    :data => {:confirm => "Are you sure?",
      :method => "delete"} %>
    </li>
    <% end %>
  </ul>
  <% else %>
  <p>There are no lessons yet!</p>
  <% end %>

  <p><%= link_to "Add a lesson", new_section_lesson_path(@section) %></p>

<p><%= link_to "Edit", edit_section_path(@section) %></p>
<p><%= link_to "Delete", section_path(@section),
:data => {:confirm => "You sure?",
  :method => "delete"} %></p>
<p><%= link_to "Return to Sections", sections_path %></p>